# 🤖 Notebook 2 — Chatbot (Ollama + PostgreSQL)
Natural language → SQL → Results → Plain English answer

In [1]:
# Cell 1 — Setup
import sys, os
sys.path.insert(0, os.path.abspath('..'))

from src.db import run_query, get_schema
from src.llm import get_sql, summarize
import pandas as pd

# Load schema once — reused across all questions
SCHEMA = get_schema()
print('✅ Ready. Schema loaded.')

✅ Ready. Schema loaded.

In [2]:
# Cell 2 — Core chat function
def ask(question: str, show_sql: bool = True):
    print(f'\n❓ Question: {question}')
    print('─' * 60)

    # Step 1: Generate SQL
    sql = get_sql(question, SCHEMA)
    if show_sql:
        print(f'📝 Generated SQL:\n{sql}\n')

    # Step 2: Run SQL
    try:
        df = run_query(sql)
        print(f'📊 Results ({len(df)} rows):')
        display(df)
    except Exception as e:
        print(f'❌ Query failed: {e}')
        return

    # Step 3: Summarize
    answer = summarize(question, sql, df.to_string(index=False))
    print(f'\n💬 Answer:\n{answer}')
    return df

In [4]:
# Cell 3 — Try questions!
ask('How many total bookings do we have?')

❓ Question: How many total bookings do we have?
────────────────────────────────────────────────────────────
📝 Generated SQL:
SELECT COUNT(*) FROM public.bookings LIMIT 50;

📊 Results (1 rows):

   count
0    500

💬 Answer:
Based on the SQL query results, our organization has **500** total bookings. The LIMIT 50 clause is used to limit the number of rows returned in the result set, but it does not affect the overall count of bookings. This means that there are 500 bookings in total, which exceeds the 50 bookings reported in the truncated result set.

   count
0    500

In [5]:
ask('What are the top 5 cities by number of properties?')

❓ Question: What are the top 5 cities by number of properties?
────────────────────────────────────────────────────────────
📝 Generated SQL:
SELECT city FROM properties GROUP BY city ORDER BY COUNT(*) DESC LIMIT 50;

📊 Results (7 rows):

          city
0       Austin
1      Chicago
2       Denver
3      Seattle
4     New York
5  Los Angeles
6        Miami

💬 Answer:
Based on the SQL results, the top 5 cities by number of properties are:

1. Los Angeles with **50** properties,
2. New York with **50** properties,
3. Seattle with **30** properties,
4. Chicago with **25** properties, and
5. Denver with **20** properties.

These cities have the highest concentration of properties, highlighting their popularity as a location for various types of properties.

          city
0       Austin
1      Chicago
2       Denver
3      Seattle
4     New York
5  Los Angeles
6        Miami

In [6]:
ask('What is the total revenue from completed bookings?')

❓ Question: What is the total revenue from completed bookings?
────────────────────────────────────────────────────────────
📝 Generated SQL:
SELECT SUM(T2.amount * (T1.checkout_date - T1.checkin_date)) AS total_revenue FROM bookings AS T1 INNER JOIN properties AS T2 ON T1.property_id = T2.property_id WHERE T1.status = 'completed' LIMIT 50;

❌ Query failed: Execution failed on sql 'SELECT SUM(T2.amount * (T1.checkout_date - T1.checkin_date)) AS total_revenue FROM bookings AS T1 INNER JOIN properties AS T2 ON T1.property_id = T2.property_id WHERE T1.status = 'completed' LIMIT 50;': (psycopg2.errors.UndefinedColumn) column t2.amount does not exist
LINE 1: SELECT SUM(T2.amount * (T1.checkout_date - T1.checkin_date))...
                   ^
HINT:  Perhaps you meant to reference the column "t1.amount".

[SQL: SELECT SUM(T2.amount * (T1.checkout_date - T1.checkin_date)) AS total_revenue FROM bookings AS T1 INNER JOIN properties AS T2 ON T1.property_id = T2.property_id WHERE T1.status = 'completed' LIMIT 50;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [7]:
ask('Which property category gets the highest average rating?')

❓ Question: Which property category gets the highest average rating?
────────────────────────────────────────────────────────────
📝 Generated SQL:
SELECT T2.category FROM reviews AS T1 INNER JOIN properties AS T2 ON T1.booking_id = T2.property_id GROUP BY T2.category ORDER BY AVG(T1.rating) DESC LIMIT 50;

📊 Results (5 rows):

    category
0      Villa
1      Condo
2     Studio
3  Apartment
4      Cabin

💬 Answer:
Based on the provided SQL results, the property category with the highest average rating is **Villa**, followed by other categories. The top 3 categories are Villa (**N/A**), Condo (**N/A**), and Studio (**N/A**) as the results don't explicitly state the actual average ratings for each category. Since only three categories have a category name mentioned, it's likely that the top-rated category is actually tied between multiple properties with the highest ratings.

    category
0      Villa
1      Condo
2     Studio
3  Apartment
4      Cabin

In [8]:
ask('Show me monthly booking counts for 2023')

❓ Question: Show me monthly booking counts for 2023
────────────────────────────────────────────────────────────
📝 Generated SQL:
SELECT EXTRACT(MONTH FROM checkin_date) AS month,
       EXTRACT(YEAR FROM checkin_date) AS year,
       COUNT(*) AS count
FROM bookings
WHERE checkin_date >= '2023-01-01' AND checkin_date <= '2023-12-31'
GROUP BY EXTRACT(MONTH FROM checkin_date), EXTRACT(YEAR FROM checkin_date)
ORDER BY month, year
LIMIT 50;

📊 Results (12 rows):

    month    year  count
0     1.0  2023.0     28
1     2.0  2023.0     23
2     3.0  2023.0     34
3     4.0  2023.0     24
4     5.0  2023.0     40
5     6.0  2023.0     33
6     7.0  2023.0     25
7     8.0  2023.0     39
8     9.0  2023.0     26
9    10.0  2023.0     31
10   11.0  2023.0     42
11   12.0  2023.0     25

💬 Answer:
The monthly booking counts for 2023 are as follows:

* January: **28** bookings
* February: **23** bookings
* March: **34** bookings
* April: **24** bookings
* May: **40** bookings
* June: **33** bookings
* July: **25** bookings
* August: **39** bookings
* September: **26** bookings
* October: **31** bookings
* November: **42** bookings
* December: **25** bookings

These numbers show a slight decrease in booking counts after the summer months, with **December** having the lowest count.

    month    year  count
0     1.0  2023.0     28
1     2.0  2023.0     23
2     3.0  2023.0     34
3     4.0  2023.0     24
4     5.0  2023.0     40
5     6.0  2023.0     33
6     7.0  2023.0     25
7     8.0  2023.0     39
8     9.0  2023.0     26
9    10.0  2023.0     31
10   11.0  2023.0     42
11   12.0  2023.0     25

In [9]:
# Cell 4 — Visualize results
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style='darkgrid')

df = run_query("""
    SELECT city, COUNT(*) AS properties
    FROM properties
    GROUP BY city
    ORDER BY properties DESC
""")

plt.figure(figsize=(10, 4))
sns.barplot(data=df, x='city', y='properties', palette='Blues_d')
plt.title('Properties by City')
plt.tight_layout()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# Cell 5 — Interactive loop
# Uncomment and run for an interactive Q&A session

# while True:
#     q = input('\nAsk a question (or q to quit): ').strip()
#     if q.lower() in ['q', 'quit', 'exit']:
#         break
#     ask(q)